sudo: required
services:
  - docker

before_install:
  - docker build -t filipemonteiro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run filipemonteiro/react-test npm test -- --coverage

after_success:
  - docker build -t filipemonteiro/multi-client ./client
  - docker build -t filipemonteiro/multi-nginx ./nginx
  - docker build -t filipemonteiro/multi-server ./server
  - docker build -t filipemonteiro/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push filipemonteiro/multi-client
  - docker push filipemonteiro/multi-nginx
  - docker push filipemonteiro/multi-server
  - docker push filipemonteiro/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "MultiDocker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-230705462750"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
